Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> set={10,20,78,53,46}
>>> set
{10, 46, 78, 20, 53}
>>> set
{10, 46, 78, 20, 53}
>>> max(set)
78
>>> min(set)
10
>>> sum(set)
207
>>> len(set)
5
>>> set1={10,10,10,34,45,56}
>>> set1
{56, 10, 34, 45}
>>> 
set.count(10)
Traceback (most recent call last):
  File "<pyshell#9>", line 2, in <module>
    set.count(10)
AttributeError: 'set' object has no attribute 'count'
>>> set1.count(10)
Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    set1.count(10)
AttributeError: 'set' object has no attribute 'count'
>>> cdsdadjhssAttributeError: 'set' object has no attribute 'counset.append(0={1}
SyntaxError: invalid syntax
>>> 
>>> s
Traceback (most recent call last):
  File "<pyshell#13>", line 1, in <module>
    s
NameError: name 's' is not defined
>>> NameError: name 's' is not definedset1
SyntaxError: invalid syntax
>>> SyntaxError: invalid syntaxset1
SyntaxError: invalid syntax
>>> set2={10,10,10,23,34}
>>> set2
{10, 34, 23}
>>> set2.count(10)
Traceback (most recent call last):
  File "<pyshell#18>", line 1, in <module>
    set2.count(10)
AttributeError: 'set' object has no attribute 'count'
>>> set2.append()={12}
SyntaxError: can't assign to function call
>>> set2.remove()
Traceback (most recent call last):
  File "<pyshell#20>", line 1, in <module>
    set2.remove()
TypeError: remove() takes exactly one argument (0 given)
>>> set2.clear()
>>> set2
set()
>>> set3={11,12,13,14,15}
>>> set3.remove(11)
>>> set3
{12, 13, 14, 15}
>>> set4={10,10,10,22,33,33}
>>> set4
{33, 10, 22}
>>> set4.sort()
Traceback (most recent call last):
  File "<pyshell#28>", line 1, in <module>
    set4.sort()
AttributeError: 'set' object has no attribute 'sort'
>>> sort(set4)
Traceback (most recent call last):
  File "<pyshell#29>", line 1, in <module>
    sort(set4)
NameError: name 'sort' is not defined
>>> set4.add(4)
>>> set4
{33, 10, 4, 22}
>>> set4.append(56)
Traceback (most recent call last):
  File "<pyshell#32>", line 1, in <module>
    set4.append(56)
AttributeError: 'set' object has no attribute 'append'
>>> set4.insert(4)
Traceback (most recent call last):
  File "<pyshell#33>", line 1, in <module>
    set4.insert(4)
AttributeError: 'set' object has no attribute 'insert'
>>> set4.apend()={12}
SyntaxError: can't assign to function call
>>> 
